import { RateLimitOptionsInterface } from './rate-limit.options.interface';

export const defaultRateLimitOptions: RateLimitOptionsInterface = {
  for: 'Express',
  type: 'Memory',
  keyPrefix: 'global',
  points: 4,
  pointsConsumed: 1,
  inMemoryBlockOnConsumed: 0,
  duration: 1,
  blockDuration: 0,
  inMemoryBlockDuration: 0,
  queueEnabled: false,
  whiteList: [],
  blackList: [],
  storeClient: undefined,
  insuranceLimiter: undefined,
  storeType: undefined,
  dbName: 'rate-limiter',
  tableName: undefined,
  tableCreated: undefined,
  clearExpiredByTimeout: undefined,
  execEvenly: false,
  execEvenlyMinDelayMs: undefined,
  indexKeyPrefix: {},
  maxQueueSize: 100,
  omitResponseHeaders: false,
  errorMessage: 'Rate limit exceeded',
  customResponseSchema: undefined,
  logger: true,
};
